<?php

declare(strict_types=1);

/**
 * AUTO-GENERATED by scripts/generate.mjs from the live OpenAPI spec.
 * Do not edit this file by hand. Regenerate with: node scripts/generate.mjs.
 *
 * The hand-written surface lives in createRoxy.php, Auth/ApiKeyAuthenticator.php,
 * and RoxyApiException.php. Everything per-tag in this file is derived from
 * specs/openapi.json + scripts/tag-descriptions.mjs (namespace aliases only).
 */

namespace RoxyAPI\Sdk;

use RoxyAPI\Sdk\Auth\ApiKeyAuthenticator;
use RoxyAPI\Sdk\Generated\Resources\AngelNumbersResource;
use RoxyAPI\Sdk\Generated\Resources\AstrologyResource;
use RoxyAPI\Sdk\Generated\Resources\BiorhythmResource;
use RoxyAPI\Sdk\Generated\Resources\CrystalsResource;
use RoxyAPI\Sdk\Generated\Resources\DreamsResource;
use RoxyAPI\Sdk\Generated\Resources\IchingResource;
use RoxyAPI\Sdk\Generated\Resources\LanguagesResource;
use RoxyAPI\Sdk\Generated\Resources\LocationResource;
use RoxyAPI\Sdk\Generated\Resources\NumerologyResource;
use RoxyAPI\Sdk\Generated\Resources\TarotResource;
use RoxyAPI\Sdk\Generated\Resources\UsageResource;
use RoxyAPI\Sdk\Generated\Resources\VedicAstrologyResource;
use Saloon\Contracts\Authenticator;
use Saloon\Http\Connector;
use Saloon\Traits\Plugins\AcceptsJson;

/**
 * Top-level RoxyAPI connector. One resource per OpenAPI tag, lazy-instantiated
 * via the __get accessor below.
 *
 * @property AngelNumbersResource $angelNumbers
 * @property AstrologyResource $astrology
 * @property BiorhythmResource $biorhythm
 * @property CrystalsResource $crystals
 * @property DreamsResource $dreams
 * @property IchingResource $iching
 * @property LanguagesResource $languages
 * @property LocationResource $location
 * @property NumerologyResource $numerology
 * @property TarotResource $tarot
 * @property UsageResource $usage
 * @property VedicAstrologyResource $vedicAstrology
 */
class Roxy extends Connector
{
    use AcceptsJson;

    /**
     * @var array<string, class-string>
     */
    private const RESOURCES = [
        'angelNumbers' => AngelNumbersResource::class,
        'astrology' => AstrologyResource::class,
        'biorhythm' => BiorhythmResource::class,
        'crystals' => CrystalsResource::class,
        'dreams' => DreamsResource::class,
        'iching' => IchingResource::class,
        'languages' => LanguagesResource::class,
        'location' => LocationResource::class,
        'numerology' => NumerologyResource::class,
        'tarot' => TarotResource::class,
        'usage' => UsageResource::class,
        'vedicAstrology' => VedicAstrologyResource::class,
    ];

    /** @var array<string, object> */
    private array $resourceCache = [];

    public function __construct(public readonly string $apiKey)
    {
    }

    public function resolveBaseUrl(): string
    {
        return 'https://roxyapi.com/api/v2';
    }

    protected function defaultAuth(): ?Authenticator
    {
        return new ApiKeyAuthenticator($this->apiKey);
    }

    /**
     * @return array<string, string>
     */
    protected function defaultHeaders(): array
    {
        return [
            'X-SDK-Client' => 'roxy-sdk-php/' . Version::VERSION,
        ];
    }

    public function __get(string $name): object
    {
        if (!isset(self::RESOURCES[$name])) {
            throw new \InvalidArgumentException(sprintf('Unknown resource "%s" on Roxy. Known: %s', $name, implode(', ', array_keys(self::RESOURCES))));
        }

        return $this->resourceCache[$name] ??= new (self::RESOURCES[$name])($this);
    }

    public function __isset(string $name): bool
    {
        return isset(self::RESOURCES[$name]);
    }
}
