<?php

declare(strict_types=1);

namespace RoxyAPI\Sdk;

/**
 * AUTO-GENERATED by scripts/generate.mjs from package.json. Do not edit manually.
 */
final class Version
{
    public const VERSION = '0.1.18';
}
